"""The twenty-eight nodes, in canonical order."""
NODES = [
    ("N",       "Specification",                "Canonical intent"),
    ("N by E",  "Requirements",                 "Requirements elaboration"),
    ("NNE",     "Domain analysis",              "Domain decomposition"),
    ("NE by N", "Conceptual architecture",      "Architectural refinement"),
    ("NE",      "Specification ↔ Production",   "Model-driven generation"),
    ("NE by E", "Interface architecture",       "API and contract design"),
    ("ENE",     "Service architecture",         "Service decomposition"),
    ("E by N",  "Implementation planning",      "Build preparation"),
    ("E",       "Production",                   "Implementation"),
    ("E by S",  "Packaging",                    "Build assembly"),
    ("ESE",     "Release engineering",          "Deployment preparation"),
    ("SE by E", "Deployment",                   "Operational rollout"),
    ("SE",      "Production ↔ Federation",      "Service publication"),
    ("SE by S", "Runtime integration",          "Environment integration"),
    ("SSE",     "Operations",                   "Operational coordination"),
    ("S by E",  "Capability integration",       "Federation onboarding"),
    ("S",       "Federation",                   "Cross-domain coordination"),
    ("S by W",  "Governance",                   "Policy coordination"),
    ("SSW",     "Compliance",                   "Organizational alignment"),
    ("SW by S", "Interoperability validation",  "Contract verification"),
    ("SW",      "Federation ↔ Verification",    "Cross-domain assurance"),
    ("SW by W", "System assurance",             "Operational verification"),
    ("WSW",     "Runtime validation",           "Monitoring and auditing"),
    ("W by S",  "Evidence collection",          "Measurement"),
    ("W",       "Verification",                 "Conformance assessment"),
    ("W by N",  "Static analysis",              "Structural verification"),
    ("WNW",     "Formal analysis",              "Proof preparation"),
    ("NW by W", "Defect localization",          "Corrective analysis"),
    ("NW",      "Verification ↔ Specification", "Specification refinement"),
    ("NW by N", "Standards refinement",         "Framework improvement"),
    ("NNW",     "Canonicalization",             "Consolidation of knowledge"),
    ("N by W",  "Specification governance",     "Normative publication"),
]
