{
  "apiVersion": "apps/v1",
  "kind": "Deployment",
  "metadata": {
    "name": "content-management"
  },
  "spec": {
    "replicas": 2,
    "selector": {
      "matchLabels": {
        "app": "content-management"
      }
    },
    "template": {
      "metadata": {
        "labels": {
          "app": "content-management"
        }
      },
      "spec": {
        "containers": [
          {
            "name": "content-management",
            "image": "gcr.io/uci/content-management:latest",
            "ports": [
              {
                "containerPort": 8080
              }
            ]
          }
        ]
      }
    }
  }
}
