{
  "apiVersion": "v1",
  "kind": "Service",
  "metadata": {
    "name": "content-management-svc"
  },
  "spec": {
    "selector": {
      "app": "content-management"
    },
    "ports": [
      {
        "protocol": "TCP",
        "port": 80,
        "targetPort": 8080
      }
    ]
  }
}
