"""Taxonomy primitives: 15 levels, kinds, bindings, invariants."""
__version__ = "0.1.0"

LEVELS = [
    "PHYSICAL", "GATE", "TRANSISTOR", "LOGIC", "MICROARCHITECTURE",
    "INSTRUCTION_SET_ARCHITECTURE", "OPERATING_SYSTEM", "ASSEMBLY",
    "HIGH_LEVEL_LANGUAGE", "APPLICATION", "FRAMEWORK", "REGISTRY",
    "LEDGER", "ARTIFACT", "GOVERNANCE", "META",
]

LEVEL_INDEX = {name: i for i, name in enumerate(LEVELS)}

KINDS = {
    "INSTRUCTION_SET_ARCHITECTURE": [
        "NOP","LOAD","STORE","MOVE","ADD","SUB","MUL","DIV","MOD","AND","OR","XOR",
        "NOT","SHL","SHR","CMP","JMP","JE","JNE","JL","JLE","JG","JGE","CALL","RET",
        "PUSH","POP","ENTER","LEAVE","INT","IRET","HLT","WAIT","YIELD","SPWN","JOIN",
        "LOCK","UNLOCK","ATOMIC","BARRIER","FENCE","DMA","MMAP","MUNMAP","PROTECT",
        "UNPROTECT","TRAP","SIGNAL","MASK","UNMASK",
    ],
    "OPERATING_SYSTEM": [
        "FORK","EXEC","WAIT","EXIT","OPEN","CLOSE","READ","WRITE","SEEK","STAT",
        "FSTAT","LSTAT","POLL","SELECT","PIPE","SOCKET","BIND","LISTEN","ACCEPT",
        "CONNECT","SEND","RECV","SHUTDOWN","MMAP","MUNMAP","MPROTECT","BRK","SBRK",
        "CLONE","UNAME","GETPID","GETPPID","GETUID","GETGID","SETUID","SETGID",
        "CHDIR","CHROOT","CHMOD","CHOWN","KILL","SIGACTION","SIGPROCMASK",
        "SIGRETURN","NANOSLEEP","CLOCK_GETTIME","GETRANDOM","MOUNT","UMOUNT",
        "PTRACE","SECCOMP","CAPGET","CAPSET",
    ],
    "ASSEMBLY": [
        "SECTION","GLOBAL","EXTERN","ALIGN","BYTE","WORD","DWORD","QWORD","ASCII",
        "ASCIZ","SPACE","EQU","SET","MACRO","ENDMACRO","INCLUDE","IF","IFDEF",
        "IFNDEF","ELSE","ENDIF","REPT","ENDR","ORG","BITS","DEFAULT","COMMON",
        "LOCAL","STRUCT","ENDSTRUCT","UNION","ENDUNION","TYPEDEF","LABEL","PROC",
        "ENDPROC","IMPORT","EXPORT",
    ],
    "HIGH_LEVEL_LANGUAGE": [
        "VARIABLE","CONSTANT","TYPE","STRUCT","UNION","ENUM","INTERFACE","CLASS",
        "OBJECT","FUNCTION","METHOD","CLOSURE","LAMBDA","GENERATOR","COROUTINE",
        "MODULE","PACKAGE","NAMESPACE","IMPORT","EXPORT","IF","ELSE","ELIF",
        "SWITCH","CASE","DEFAULT","WHILE","DO","FOR","FOREACH","BREAK","CONTINUE",
        "RETURN","YIELD","AWAIT","ASYNC","TRY","CATCH","FINALLY","THROW","RAISE",
        "ASSERT","WITH","USING","MATCH","PATTERN","GUARD","DEFER","GO","CHAN","SELECT",
    ],
    "APPLICATION": [
        "CLI","GUI","TUI","WEB","MOBILE","DESKTOP","SERVER","DAEMON","SERVICE",
        "WORKER","SCHEDULER","PROXY","GATEWAY","ROUTER","BROKER","QUEUE","CACHE",
        "STORE","INDEX","REGISTRY","REPOSITORY","PIPELINE","ORCHESTRATOR",
        "CONTROLLER","OPERATOR","AGENT","SIDECAR","ADAPTER","CONNECTOR","PLUGIN",
        "EXTENSION","MIGRATOR","SEEDER","PARSER","COMPILER","INTERPRETER",
        "TRANSPILER","LINTER","FORMATTER","BUNDLER","MINIFIER","TESTER","BENCHMARK",
        "PROFILER","DEBUGGER","TRACER","LOGGER","METRICS","ALERTER",
    ],
    "FRAMEWORK": [
        "RUNTIME","LIBRARY","SDK","TOOLKIT","PLATFORM","ENGINE","VM","CONTAINER",
        "ORCHESTRATOR","MESH","BUS","GATEWAY","PROXY","REGISTRY","CONFIG","SECRETS",
        "IDENTITY","POLICY","OBSERVABILITY","TRACING","METRICS","LOGGING",
        "ALERTING","CI","CD","GITOPS","IAC","PAAS","IAAS","FAAS","CAAS","SAAS",
        "BAAS","DAAS","SECAAS",
    ],
    "REGISTRY": [
        "SOURCE","AUTHORITY","PUBLICATION","LOCATOR","ENTRY","AXIS","SNAPSHOT",
        "VERSION","CHANGELOG","DEPRECATION","ALIAS","RELATION","TRIANGULATION",
        "COVERAGE","GAP","CLOSURE","RESIDUAL","INDEX","CATALOG","MANIFEST",
        "ATTESTATION","SIGNATURE","PROVENANCE","LINEAGE",
    ],
    "LEDGER": [
        "PU","OBJECTIVE","SCOPE","CONSTRAINT","ASSUMPTION","CLAIM","EVIDENCE",
        "LINK","TRACEABILITY","GATE","CRITERION","METRIC","AUDIENCE","DECISION",
        "RISK","CONTROL","TEST","RESULT","FINDING","REMEDIATION","RETEST",
        "SIGN_OFF","OWNER","VERSION","SNAPSHOT_REF",
    ],
    "ARTIFACT": [
        "DOSSIER","DECK","WORKBOOK","MANIFEST","CERTIFICATE","COVERAGE",
        "GAP_REGISTER","CLOSURE_LOG","SNAPSHOT","CHAIN","ATTESTATION",
        "SIGNATURE","PROVENANCE","LINEAGE","INDEX","CATALOG","REPORT",
        "SUMMARY","BRIEF","MATRIX","REGISTER","JOURNAL","TRACE","AUDIT",
    ],
    "GOVERNANCE": [
        "POLICY","STANDARD","CONTROL","FRAMEWORK","REGULATION","DIRECTIVE",
        "GUIDELINE","PROCEDURE","PROCESS","GATE","APPROVAL","SIGN_OFF","REVIEW",
        "AUDIT","ATTESTATION","CERTIFICATION","ACCREDITATION","ASSESSMENT",
        "EVALUATION","MATURITY","CAPABILITY","COMPETENCY","ROLE",
        "RESPONSIBILITY","ACCOUNTABILITY","AUTHORITY","DELEGATION","ESCALATION",
        "EXCEPTION","WAIVER","REMEDIATION","SANCTION",
    ],
    "META": [
        "FRAMEWORK","META_FRAMEWORK","META_MODEL","META_LANGUAGE","META_SEMANTICS",
        "META_THEORY","META_LOGIC","META_MATHEMATICS","META_ONTOLOGY",
        "META_EPISTEMOLOGY","META_AXIOM","META_POSTULATE","META_PRIMITIVE",
        "META_GRAMMAR","META_LEXICON","META_SORT","META_JUDGMENT","META_PROOF",
        "META_MODEL","META_INTERPRETATION","META_COMPLETENESS","META_SOUNDNESS",
        "META_CONSISTENCY","META_DECIDABILITY","META_EXPRESSIVENESS",
        "META_COMPOSITIONALITY","META_REFLEXIVITY","META_RECURSION",
        "META_COINDUCTION","META_FIXED_POINT","META_INVARIANT","META_CONTRACT",
        "META_REFINEMENT","META_ABSTRACTION","META_EMERGENCE",
    ],
}

INVARIANTS = [
    "EVERY_LEVEL_DEPENDS_ON_LEVEL_BELOW",
    "EVERY_LEVEL_DEFINES_TERMS_FOR_LEVEL_ABOVE",
    "NO_LEVEL_CLAIMS_UNSCOPED_COMPLETENESS",
    "NO_LEVEL_EMITS_UNBOUNDED_COMPLETENESS_TOKEN",
    "EVERY_CLAIM_TRACES_TO_EVIDENCE",
    "EVERY_ARTIFACT_TRACES_TO_LEDGER",
    "EVERY_LEDGER_TRACES_TO_REGISTRY",
    "EVERY_REGISTRY_TRACES_TO_SOURCE",
    "EVERY_SOURCE_IS_BOUNDED_AND_VERSIONED",
    "EVERY_GAP_IS_NAMED",
    "EVERY_RESIDUAL_IS_REPORTED",
    "EVERY_SNAPSHOT_IS_IMMUTABLE",
    "EVERY_SIGN_OFF_IS_NAMED",
    "EVERY_CLOSURE_IS_VERSIONED",
    "EVERY_RECURSION_HAS_A_FIXED_POINT_OR_IS_COINDUCTIVE",
]

FORBIDDEN_TOKENS = [
    "complete", "completeness", "exhaustive", "all_known",
    "all possible", "for all industries in existence",
]

def level_of(name):
    return LEVEL_INDEX.get(name)

def is_kind(level_name, token):
    return token in KINDS.get(level_name, [])

def scan_forbidden(obj):
    """Return list of (path, token) where forbidden tokens appear."""
    hits = []
    def walk(o, path=""):
        if isinstance(o, dict):
            for k, v in o.items():
                if k.lower() in FORBIDDEN_TOKENS and v is True:
                    hits.append((path + "/" + k, k))
                walk(v, path + "/" + str(k))
        elif isinstance(o, list):
            for i, v in enumerate(o):
                walk(v, path + "/" + str(i))
        elif isinstance(o, str):
            low = o.lower()
            for t in FORBIDDEN_TOKENS:
                if t in low:
                    hits.append((path, t))
    walk(obj)
    return hits
