#!/usr/bin/env python3
"""Regenerate artifacts that depend on spec regimes.

Does NOT refresh the attestation baseline — that is a separate step.
Run `python packages/gaps/gaps.py --save-baseline` explicitly if needed.
"""
from __future__ import annotations
import json
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "packages" / "buildability" / "src"))

from buildability import spec_from_file, evaluate


CORPORA = ["mesh/specs_uci", "mesh/specs_expanded"]


def regime_distribution(corpus: Path) -> dict:
    specs = [spec_from_file(p) for p in sorted(corpus.glob("*.json"))]
    return dict(Counter(evaluate(s).regime for s in specs))


def sync_bridge() -> None:
    bridge = ROOT / "bridge" / "report.json"
    report = json.loads(bridge.read_text()) if bridge.exists() else {"sections": []}
    by_name = {s["name"]: s for s in report["sections"]}
    for name in CORPORA:
        corpus = ROOT / name
        if not corpus.exists():
            continue
        dist = regime_distribution(corpus)
        count = len(list(corpus.glob("*.json")))
        if name in by_name:
            by_name[name]["count"] = count
            by_name[name]["regimes"] = dist
        else:
            report["sections"].append({"name": name, "count": count, "regimes": dist})
    bridge.parent.mkdir(exist_ok=True)
    bridge.write_text(json.dumps(report, indent=2, default=str) + "\n")


def sync_pinning_test() -> None:
    tp = ROOT / "packages" / "buildability" / "tests" / "test_claims.py"
    if not tp.exists():
        return
    s = tp.read_text()
    idx = s.find("def test_expanded_corpus_regimes_are_pinned")
    if idx == -1:
        return
    end = s.find("\ndef ", idx + 1)
    if end == -1:
        end = len(s)
    d = ROOT / "mesh" / "specs_expanded"
    actual = {p.stem: evaluate(spec_from_file(p)).regime
              for p in sorted(d.glob("*.json"))}
    lines = "\n".join(f'        "{n}": "{r}",' for n, r in sorted(actual.items()))
    body = f'''def test_expanded_corpus_regimes_are_pinned():
    """Regenerated by scripts/regime_sync.py. Do not edit by hand."""
    from pathlib import Path as _P
    from buildability import spec_from_file as _sf, evaluate as _ev
    d = _P(__file__).resolve().parents[3] / "mesh" / "specs_expanded"
    expected = {{
{lines}
    }}
    for path in sorted(d.glob("*.json")):
        v = _ev(_sf(path))
        assert v.regime == expected[path.stem], (
            f"{{path.stem}}: got {{v.regime}}, want {{expected[path.stem]}}"
        )
'''
    tp.write_text(s[:idx] + body + s[end:])


def main() -> int:
    sync_bridge()
    sync_pinning_test()
    print("regime_sync complete (baseline not refreshed)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
