#!/usr/bin/env bash
# Declare the ENGINES map and write it to a machine-readable file.
# This is the source of truth for which toolchain a given language,
# runtime, package manager, or framework resolves to.

set -euo pipefail

declare -A ENGINES=(
  ["python"]="python3"
  ["rust"]="cargo"
  ["go"]="go"
  ["swift"]="swiftc"
  ["node"]="node"
  ["perl"]="perl"
  ["ruby"]="ruby"
  ["php"]="php"
  ["java"]="javac"
  ["kotlin"]="kotlinc"
  ["scala"]="scalac"
  ["groovy"]="groovyc"
  ["c"]="clang"
  ["cpp"]="clang++"
  ["fortran"]="gfortran"
  ["haskell"]="ghc"
  ["erlang"]="erlc"
  ["elixir"]="elixirc"
  ["lua"]="lua"
  ["tcl"]="tclsh"
  ["r"]="Rscript"
  ["julia"]="julia"
  ["bash"]="bash"
  ["zsh"]="zsh"
  ["powershell"]="pwsh"
  ["dotnet"]="dotnet"
  ["dart"]="dart"
  ["typescript"]="tsc"
  ["objectivec"]="clang"
  ["ocaml"]="ocamlopt"
  ["nim"]="nim"
  ["zig"]="zig"
  ["crystal"]="crystal"
  ["wasm"]="wasm-pack"
  ["cuda"]="nvcc"
  ["opencl"]="clang"
  ["verilog"]="iverilog"
  ["vhdl"]="ghdl"
  ["matlab"]="matlab"
  ["wolfram"]="wolframscript"
  ["smalltalk"]="gst"
  ["prolog"]="swipl"
  ["clojure"]="clj"
  ["scheme"]="guile"
  ["commonlisp"]="sbcl"
  ["fsharp"]="fsharpc"
  ["reasonml"]="rebuild"
  ["ada"]="gnatmake"
  ["pascal"]="fpc"
  ["cobol"]="cobc"
  ["assembly"]="nasm"
  ["ml"]="ocaml"
  ["jsonnet"]="jsonnet"
  ["yaml"]="yq"
  ["graphql"]="graphql"
  ["sql"]="sqlite3"
  ["nosql"]="mongo"

  ["docker"]="docker"
  ["kubernetes"]="kubectl"
  ["terraform"]="terraform"
  ["ansible"]="ansible-playbook"
  ["nix"]="nix-build"
  ["bazel"]="bazel"
  ["make"]="make"
  ["cmake"]="cmake"
  ["gradle"]="gradle"
  ["maven"]="mvn"

  ["poetry"]="poetry"
  ["pip"]="pip"
  ["conda"]="conda"
  ["npm"]="npm"
  ["pnpm"]="pnpm"
  ["yarn"]="yarn"
  ["composer"]="composer"

  ["helm"]="helm"
  ["ipfs"]="ipfs"
  ["nats"]="nats-server"
  ["redis"]="redis-server"
  ["postgres"]="psql"
  ["mysql"]="mysql"
  ["sqlite"]="sqlite3"
  ["mongodb"]="mongod"
  ["influxdb"]="influxd"
  ["grafana"]="grafana-server"
  ["prometheus"]="prometheus"

  ["openai"]="openai"
  ["huggingface"]="transformers-cli"
  ["torch"]="python3 -m torch.utils.collect_env"
  ["tensorflow"]="python3 -c 'import tensorflow as tf;print(tf.__version__)'"
  ["jax"]="python3 -c 'import jax;print(jax.__version__)'"
  ["onnx"]="onnxruntime"
  ["mlflow"]="mlflow"
  ["ray"]="ray"
  ["langchain"]="python3 -m langchain"
  ["autogen"]="python3 -m autogen"

  ["quantum_qiskit"]="python3 -m qiskit"
  ["quantum_cirq"]="python3 -m cirq"
  ["quantum_braket"]="braket"
  ["quantum_ionq"]="ionq"
  ["quantum_qsharp"]="dotnet run --project qsharp"
  ["quantum_xanadu"]="python3 -m pennylane"

  ["tensors"]="python3 -c 'import torch, tensorflow; print(\"tensors ok\")'"
  ["nltk"]="python3 -m nltk.downloader punkt"
)

# Write each entry as a line: name<TAB>command
out="$(dirname "$0")/engines.tsv"
: > "$out"
for key in "${!ENGINES[@]}"; do
    printf '%s\t%s\n' "$key" "${ENGINES[$key]}" >> "$out"
done
sort -o "$out" "$out"
echo "wrote $(wc -l < "$out") engine entries to $out"
